### PR TITLE
Version bump to try to fix npm i

### PR DESCRIPTION
**Pull request by awikkerink**
Will also need a new 3.0.1 release.

### CODE REVIEW

**Comment by awikkerink** [comment]
ping @rcausey

**Comment by awikkerink** [comment]
@rcausey could you add a 3.0.1 release? I don't have write permissions on this repo

**Comment by rcausey** [comment]
@awikkerink I just gave you permissions on the repo, in case you need to try other things

**Comment by awikkerink** [comment]
:cool: thanks

**Pull request merged**
